# Generated by Django 4.2.13 on 2024-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carimages',
            options={'verbose_name_plural': 'Car Images'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name_plural': 'Car Model'},
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
