# Generated by Django 4.2.13 on 2024-06-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_features_alter_car_price_per_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Color',
            new_name='color',
        ),
    ]
