# Generated by Django 4.2.13 on 2024-06-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_make_car_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.DeleteModel(
            name='Make',
        ),
    ]
