# Generated by Django 4.2.13 on 2024-06-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_make_delete_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
